services:
  api:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      PORT: 3366
      DB_CONNECTION_URI: mysql://user:password@db:3306/nodedata
    ports:
      - 3366:3366
    expose:
      - '3366'
  
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'nodedata'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3396:3306'
    expose:
      # Opens port 3396 on the container
      - '3396'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

# Names our volume
volumes:
  my-db:
